sudo: required
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/com/opengamma/margining
# install
before_install:
  - echo "MAVEN_OPTS='-Xms512m -Xmx2g'" > ~/.mavenrc
install:
  - mvn --version
script:
  - mvn install -e -B
# deploy
after_success:
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then mvn deploy -Ddist -DaltDeploymentRepository="og-public-release::default::https://api.bintray.com/maven/opengamma/releases/ServiceClient/" --settings .github/deploy-settings.xml; fi
# secure keys for DEPLOY_USER and DEPLOY_PASSWORD
env:
  global:
  - secure: l7++24UUySPCyybxxH1rC2W3Mew4TcwAOZkTwh3KCio1r8weiXYjRc/q5Isf7SVABIVS05DfpGFqx2h3yee11aRy1zROBz0meKgY7sRfipwN4h3xtrSiZEx86gTz7kjaxHXzX+DMfFY3p7oex16ZHN7fTNw55POmLroRFFHF9HuXnfOZE/vX8JlbOX8yiOADGIiVEH+u4Rt6tbNzrdHdeKLBszqvxvZShys7h9Hwhl5J00/DYYoFYa7oj6rVl6tejbQJIO+UeWZh/osngDTURQ4zD0uG2vPES9lXeVc61JTkxUvvuwg32wR7sHi81Gvh4DVuDhbLZx9C5SrloPNAW2JzUx7rVwvR4K4TvMH0H30VNEwQC9KGwODzedIglQZkm9sW2ytiZTRjeiJphV35n+TKXER+X80QGzuLBDsDS2ywummQvO5OVFqxw9hJmHQdCGQtLVgvfwLyv9ABtNNs+19JY9NyQix9Gl5LRGUYe3oo9UALLeqXfDNFpMEVjlVCAEMQ3gX44+FRAbZzHGNpcHBDowx5rYnkVfufl28c13Lr7yXwJdqg6kqaB97ez5RgYbYevuQ+rzX5waYTPrOsyyeijjlZEhIOilsnh8rzTdEJ/Mc5D87KbznGpxX74MeZ1Dd175+kfu72kaaPJh7gm/ISIvWJVEuy0EWieid5xX0=
  - secure: UyY+hXUK0Pd9Asy3mMysu4jd1YT7rV/vPoLE28Mtqx/ONYvczvApTnFwcoTrvprcHZRLFswCHerqyVEnOY0+MnEDO8XUkDKjIjxSH7uQHjuyZRiwjbvFwAAfZpkYbq6OyN5L5knGKAVnqlBDx3RBJAod4QSzam5MofAkHf9Rahg16vwWiQIb2vKjWJSClc3ZTsWlBhi7y2Mih5kjdg1gD80w42hc+PFpL5OfVkB+fRQCu2rVuw59miRAoypzgIUaCWT3QJxit6u9AnYzR+AB5YIYnOkJKVR4UehLlhbYB+8pFv9iNVgUaigp8fPrMWNKmgD1JFG01Gg1kVrBFW0VVeSa4mtrbu1ar1kl0zrS/62tek7QMlZsE5vLCqfdJqaz6U8jMVTgoVeV3G7tFSgidSbtWzyIWyi4H0AcQAFs3n9BhzxBcHDasm9Q5WU1QNAlqWbWXOSa2V5Hw1CdJt2hgo8tsWZ/MyQ4hHLEH79hG7AD3z/8Pulh/QGyzu3qD6Nri8G0xfq/dDYNn2rtDZ+HrZ+KhQGPHJxgmVO8P8frZDLwXlB1fHps2Lz+7tQlMiwPf6W3VjMiiJUDT9LBKXptZdBrdLHCI36YKEneRMzr0M2K5juxKhVcd7/15zb6KWA0Xhsqtw3S6rv8LON+CRRkNWu2haAIHOs/6+gNOswhkbk=
